name: Build Windows Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16' # Versione compatibile con electron 8

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run webpack

    - name: Build Windows package
      run: npm run build:win
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false # Disabilita code signing se non configurato

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-package
        path: |
          release/*.exe
          release/*.zip
